version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: hufs
            password: capstone
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hufs
      POSTGRES_PASSWORD: capstone
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
